name: Release a new version

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: "Version to bump?"
        required: true
        default: patch
        options:
          - patch
          - minor
          - major

concurrency:
  group: bumpversion-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

jobs:
  bump_the_version:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: "Checkout repository"
        uses: 'actions/checkout@v3'
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: "Install bump2version"
        run: pip install --upgrade bump2version

      - name: "Bump the version"
        run: |
          git config --global user.name "keremdokumaci"
          git config --global user.email "dokumaci.kerem@gmail.com"
          bump2version ${{ github.event.inputs.version }}
          git push --follow-tags
  release:
    name: Create Release
    runs-on: 'ubuntu-latest'
    steps:
      - name: "Checkout repository"
        uses: 'actions/checkout@v3'
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
          token: ${{ secrets.GH_ACCESS_TOKEN }}
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          check-latest: true
      - name: Get OS and arch info
        run: |
          GOOSARCH=${{matrix.goosarch}}
          GOOS=${GOOSARCH%/*}
          GOARCH=${GOOSARCH#*/}
          BINARY_NAME=${{github.repository}}-$GOOS-$GOARCH
          echo "BINARY_NAME=$BINARY_NAME" >> $GITHUB_ENV
          echo "GOOS=$GOOS" >> $GITHUB_ENV
          echo "GOARCH=$GOARCH" >> $GITHUB_ENV
      - name: Build
        run: |
          go build -o "$BINARY_NAME" -v
      - name: Release with Notes
        uses: softprops/action-gh-release@v1
        with:
          body_path: ".github/RELEASE-TEMPLATE.md"
          draft: true
          files: ${{env.BINARY_NAME}}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
  publish:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: "Checkout repository"
        uses: 'actions/checkout@v3'
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
          token: ${{ secrets.GH_ACCESS_TOKEN }}
      - name: Ping endpoint
        run: curl "https://proxy.golang.org/github.com/keremdokumaci/comandante/${{ github.event.inputs.version }}/$(git describe HEAD --tags --abbrev=0).info"
